### PR TITLE
IE 10+ device width

### PR DESCRIPTION
**Pull request by purplecabbage**
The same original blog post has been updated stating that this needs to be applied past IE10.0

http://mattstow.com/responsive-design-in-ie10-on-windows-phone-8.html#the-fix

### CODE REVIEW

**Comment by purplecabbage** [comment]
What's the deal with circle-ci? This is not an issue with this pr.

**Comment by mwbrooks** [comment]
Today, Circle CI has been having issues pulling down our signing keys in order to compile the app. It's not an issue with your PR.

**Comment by mwbrooks** [comment]
@timkim do you want this PR merged into `master` or `dev`?

**Comment by purplecabbage** [comment]
@timkim or both ...

**Comment by timkim** [comment]
I'll merge this into dev and see how it does. Not sure about Circle CI - I looked into it and I can't quite figure out why it doesn't like our dev-keys credentials anymore.

**Comment by purplecabbage** [comment]
Probably because all apple certs expired recently.

**Comment by purplecabbage** [comment]
Actually the error is that circleci cannot access the private repo:
ERROR: Repository not found.
fatal: Could not read from remote repository.

**Comment by timkim** [comment]
Ok, I merged it into [dev](https://github.com/phonegap/phonegap-app-developer/tree/dev).

@purplecabbage Ya, it doesn't seem to recognise the ssh key it uses to clone down the private repo. I've checked on github for valid ssh keys and it seems to have the _correct_ one.

**Comment by purplecabbage** [comment]
This was merged to dev, at some point it will show up in master, .. closing.

**Comment by timkim** [comment]
It's in there already: https://github.com/phonegap/phonegap-app-developer/commit/31c911cd1786d0f3d9e69bf5ecd8e888f718769e

**Pull request closed without merging**
