### PR TITLE
!!!For discussion only!!! DO NOT MERGE

### PR DESCRIPTION
**Pull request by devgeeks**
Had a shot at the login / apps fetching flow

Not sure how far along you were, @wildabeast, but wanted to have a discussion on loading state flow etc...

### CODE REVIEW

**Comment by devgeeks** [comment]
This is what it looks like...

phonegap-app-developer--login-apps-flow-1

- Logging in causes a modal (though in reality that would be overlaid with the inAppBrowser handling auth)
- Once an access_token is returned, the modal is removed and the user redirected to `./cloud/user/<accessToken>`
- The `./cloud/user` page then displays a loading message in place of its content until the apps are loaded

**Comment by wildabeast** [comment]
@devgeeks this all looks reasonable to me... made a comment inline, trivial matter though.

**Comment by devgeeks** [comment]
OK, then I am going to merge this and go ahead with it (unless you have started working on this somewhere else?)

**Comment by wildabeast** [comment]
👍

**Pull request merged**
